baseURL = "https://guardianhubx.com/blog/"
relativeURLs = false
canonifyURLs = true

languageCode = "es-es"
title = "GuardianHubX Blog"
theme = "PaperMod"
publishDir = "public"
uglyURLs = false

[params]
  env = "production"
  defaultTheme = "light" # Fondo blanco
  showReadingTime = true
  disableThemeToggle = true # No permitir cambiar a modo oscuro
  mainSections = ["blog"]

[params.assets]
  disableFingerprinting = true
  favicon = "/favicon.ico"
  customCSS = ["css/custom.css"]
  customJS = []
  googleFonts = ["Poppins"]